### ISSUE TITLE
t_vs_SE

### ISSUE THREAD

**Issue by CG1122** [CG1122/TESTING#3]
| Property  | Value |
|---|---|
|Title | This is the title of my long output| 
| Footnote| Insert a footnote here|
| QC Method | Double program |

```YAML
TITLE: This is the title of my long output
FOOTNOTE:  Insert a footnote here
QC_METHOD: Double program
```
